# Generated by Django 5.1.7 on 2025-03-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='image',
            field=models.ImageField(default=5, upload_to='trainee/imgs'),
            preserve_default=False,
        ),
    ]
