# Generated by Django 5.1.7 on 2025-03-13 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('trainee', '0003_trainee_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
